[package]
name = "novemberfork"
version = "0.1.0"
authors = ["Matt Carter"]
readme = "README.md"
homepage = "https:/novemberfork.io/"
repository = "https://github.com/0xDegenDeveloper/Novemberfork"
description = "---"

[dependencies]
# openzeppelin = ".src/openzeppelin"
starknet = "2.0.2"
# oz = { git = "https://github.com/OpenZeppelin/cairo-contracts/" }
# sierra-compile = "starknet-sierra-compile src/lib.cairo sierra/rbits.json"

[[target.starknet-contract]]
allowed-libfuncs = true
allowed-libfuncs-list.name = "experimental"
